travis:
  secure:
    BINSTAR_TOKEN: AjAtsDufmH5aV7QQgodh9sowWAQ8IluTfuryI/bjLx8mrek1sIFZnLOaEPkDsZu2aLrZ7T+c3IJrDGmsgNXE2RJDcdLWlZRMVIgE/R92CWgh3NRy27ZHZIM4bHcgx56sg9/9rojYv++cSmrcOUS7dP1SWcjbzkTLy4Wk2i05dsiYH8JrNtZgV+DiC7ln7VjrSlmqmyWbVMRLp8UGtyKgQ1wop0Q/7HVAFillBWJVb2W5G3ilPsozTSlf9MkpCyqsGLpAo9FS58HEl0Ogdf3W6ZgrGpXPteiWw9tPGGvyjv5Q1FgxYrXjv5Yjcgaw/YPrD26H0bpd9o/9OHRoZIflyp76Cxc2t65lApp0HIlvZLZuTyPaFiwmNU9f7wOzL537Bk4aW+fpj9O72mGXUKZwjYAZQf6YxdNPWscyh4FYn6q3gsTODIjqEtAjOrftMySsEzPGqjW8dYAi97t1A8Pgo+zC0tYXmThTCGlJyKiO7ZyXX3rVdrMXvuhyNT6FqP5F3X7bp450V3WfU5lxBsFwfEsRn4gabfk9kB7ZxTMFLExOBRjsgJpECyPIfTIS4uBB0jhkdsZdtMXoXV3KAH5s2+kVkrWzm07jeT61H+qfe93CPHe9+oibhq7hEXWf1SKtd8bPXkg1TLHhPg7feJvzl/+qgYypyqaKuhqJwlWuIl0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
